version: '3.8'

services:
  public_api:
    build:
      context: ./public_api  
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  private_api:
    build:
      context: ./private_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
